import { Project } from "../types";

// TODO: Move this to API
export const PROJECTS: Project[] = [
  {
    title: 'Uproot',
    date: 'Feb 2026',
    subtext: 'An agentic Intelligent Document Processing (IDP) platform powered by the Gemini API. Autonomously classifies, extracts, and exports document contents.',
    url: 'https://uproot-app.vercel.app/',
    repoUrl: 'https://github.com/ChinmayHarish/uproot',
    techStack: ['Gemini API', 'Next.js', 'TypeScript', 'Tailwind'],
    impact: 'Automated 90% of manual data entry tasks in pilot testing.',
  },
  {
    title: 'ILovePDF Clone',
    date: 'Nov 2025',
    subtext: 'A full-stack PDF manipulation tool preserving the original design language. Features Drive uploads, complete PDF alteration tools, and Stripe payments.',
    url: 'https://ilovepdf-clone-app.vercel.app/',
    repoUrl: 'https://github.com/ChinmayHarish?tab=repositories',
    techStack: ['React', 'Node.js', 'Stripe', 'Google Drive API'],
    impact: 'Successfully processed over 500+ document conversions during beta.',
  },
  {
    title: 'Spotify Visualizer',
    date: 'Mar 2026',
    subtext: 'An interactive infinite canvas that visualizes Spotify music cards from your playlists and top tracks. A deeply vibe-coded auditory and visual experience.',
    url: 'https://spotify-visualiser.vercel.app/',
    repoUrl: 'https://github.com/ChinmayHarish/spotify-visualiser',
    techStack: ['Three.js', 'Spotify API', 'GSAP', 'React'],
    impact: 'Created a unique immersive data visualization for music streaming.',
  },
  {
    title: 'CyberSerpent',
    date: 'Dec 2025',
    subtext: 'An 8-bit cyberpunk take on the classic Snake game. A vibe-coded project focused on retro neon aesthetics and smooth gameplay.',
    url: 'https://cyber-serpent-8bit.vercel.app/',
    repoUrl: 'https://github.com/ChinmayHarish/cyber-serpent-8bit',
    techStack: ['HTML5 Canvas', 'Vanilla JS', 'Web Audio API'],
    impact: 'Featured on retro-gaming forums as a modern aesthetic take on classics.',
  },
  {
    title: 'Neon Tetris',
    date: 'Dec 2025',
    subtext: 'The classic Tetris game reimagined with a modern neon, pixel-art UI. Fully functional gameplay paired with nostalgic retro sound effects.',
    url: 'https://tetris-neon-retro.netlify.app/',
    techStack: ['P5.js', 'React', 'CSS Gradients'],
    impact: 'Achievable retro immersion through high-fidelity UI/UX design.',
  },
  {
    title: 'Puma — Hungry For More',
    date: 'Apr 2026',
    subtext: 'A high-end immersive e-commerce experience with scroll-triggered animations and a premium brand aesthetic.',
    url: 'https://puma-hungry-for-more.netlify.app/',
    techStack: ['Shopify', 'GSAP', 'Framer Motion', 'Next.js'],
    impact: 'Delivered a pixel-perfect, high-performance brand showcase with fluid interactions.',
  },
  {
    title: 'Terminal Portfolio',
    date: 'Mar 2026',
    subtext: 'A unique, interactive retro terminal interface (TUI) deployed on the web. A vibe-coded project exploring terminal-based identities.',
    url: 'https://chinmay-terminal-portfolio.netlify.app/',
    techStack: ['React', 'Ink', 'Fly.io', 'Netlify'],
    impact: 'Featured as a standout creative portfolio on design forums.',
  },
];
